### ISSUE TITLE
사용자 팔로우를 위한 api 및 SSE를 통한 실시간 알림 기능 개발

### ISSUE THREAD

**Issue by stoneHee99** [Kernel360/f1-Yigil#103]
### 📝Description
사용자 팔로우 팔로잉 기능 및 실시간 알림을 위한 기능을 개발 및 적용합니다.

### ✅Task
- [x] 사용자를 팔로우 / 취소 하는 api 추가
- [x] 사용자가 팔로우하는 게시글 목록 api 추가
- [ ] 사용자를 팔로우하는 사용자 / 사용자가 팔로잉 하는 사용자 목록 api 추가
- [x] 실시간 알림을 위한 SSE 기능 추가

### ✍️Additional
크리스마스 연휴동안 천천히 만들어보겠습니다..ㅎㅎ
