### ISSUE TITLE
포스트와 스팟, 코스 CRUD 및 테스트 코드 작성

### ISSUE THREAD

**Issue by minson96** [Kernel360/f1-Yigil#117]
### 📝Description
- 스팟 코스 포스트에 관한 CRUD 작성을 진행하고 테스트 코드 작성을 진행합니다.
### ✅Task
- [x] 스팟 CRUD 구현 및 테스트 코드 작성
- [x] 코스 CRUD 구현 및 테스트 코드 작성
- [x] 포스트 CRUD 구현 및 테스트 코드 작성
