### ISSUE TITLE
메인 페이지 캐러셀(슬라이더) 구현

### ISSUE THREAD

**Issue by davidktlee** [Kernel360/f1-Yigil#120]
### 📝Description
메인 페이지의 최상위 위치에서 사용할 캐러셀 컴포넌트 작성

### ✅Task
- [ ] 스타일 작성
- [ ] 캐러셀 기능 구현
  - [ ] 버튼을 이용한 넘기기 기능 (버튼 클릭을 통한 스크롤 기능)
  - [ ] 드래그를 이용한 넘기기 기능 (마우스를 이용한 드래그 기능 -> 모바일의 경우 터치를 이용한 드래그 기능)

### ✍️Additional
- 메인에 존재하는 캐러셀 컴포넌트를 다른 컴포넌트에서 사용하지는 않을 것으로 예상되기 때문에 재사용성을 고려하지는 않아도 될 것 같음
- 피그마 디자인 시안에 따라 최초 사진 일 경우 우측 버튼 존재 / 중간 사진 일 경우 좌,우 버튼 존재 예상 / 마지막 사진 일 경우 좌측 버튼 존재 예상
- 외부 라이브러리 사용하지 않고 구현 해 보고 디자인 처럼 되지 않을 시 외부 라이브러리 사용 예정

**Comment by davidktlee** [comment]
초기에 drag 이벤트를 감지해서 구현했으나 캐러셀 요소가 `link` 요소일 경우에 웹에서 드래그 시 링크가 눌려 이동되는 현상 발생으로 
`embla carousel`라이브러리를 통해 구현함.
그러나 디자이너 변경에 따른 디자인 변경으로 캐러셀이 디자인 상 사라져 issue 닫음..
