### ISSUE TITLE
모노 모듈 -> 멀티 모듈로 마이그레이션 작업

### ISSUE THREAD

**Issue by stoneHee99** [Kernel360/f1-Yigil#131]
### 📝Description
현재 `Monolothic` 구조로 되어있는 프로젝트 구조를 멀티 모듈의 구조로 변경합니다.

### ✅Task
- [x] 기존의 프로젝트를 `yigil-api` 모듈로 마이그레이션
- [ ] 추가적인 모듈 생성 및 구조 생성 `yigil-admin`, `yigil-batch` 등등...
- [x] 공통적으로 필요한 코드를 어떻게 관리해야 할지 논의 필요

### ✍️Additional
멀티 모듈에 대해 궁금한 사항이나 전해주실 의견 있으시면 언제든 공유주시면 감사드리겠습니다.
