### ISSUE TITLE
디자인 변경으로 인한 홈 페이지 재작성

### ISSUE THREAD

**Issue by hatchling13** [Kernel360/f1-Yigil#163]
### 📝Description
새롭게 변경된 디자인에 따라 홈 페이지를 재작성합니다.

### ✅Task
- [x] '경로/장소 목록을 확인할 수 있는 화면'과 '주변 지도를 확인할 수 있는 화면' 사이의 이동을 위한 UI를 작성합니다.
- [x] 각 경로/장소에 대한 정보 확인 및 세부 내용을 확인할 수 있는 화면으로 이동하기 위한 컴포넌트를 작성합니다.
- [x] 경로/장소를 표시하는 컴포넌트를 가로 스크롤 가능한 목록 형태로 보여줄 수 있고, 분류에 따라 모아볼 수 있는 컴포넌트를 작성합니다.
- [x] 새로운 장소/경로를 작성하기 위한 [Floating Action Button](https://m3.material.io/components/floating-action-button/overview)을 작성합니다.

### ✍️Additional
- 헤더의 경우, 이미 관련된 결과물이 존재하여 해당 작업을 진행하시던 @davidktlee 님께서 계속 맡아 작업하실 예정입니다.
- 디자인이 확정되지 않아 이후 변경될 가능성이 있으므로, 최대한 변경에 유연하게 작업할 필요가 있습니다.

**Comment by hatchling13** [comment]
#173 에서 작성한 '추가로 할 일'을 여기에도 기록합니다.

### 추가로 할 일

1. 접속한 URL 상태에 따라 Link 컴포넌트의 스타일을 지정해야 합니다.
2. 게시글 목록의 '더보기'에 상호작용 기능을 추가해야 합니다(현재 디자인 상 정해진 바 없음).
3. 게시글 정보 중 댓글 수, 좋아요 수, 평점을 표시해야 합니다.
4. 각 게시글 컴포넌트에 상호작용 기능을 추가해야 합니다(상세 페이지 이동).
5. FAB에 상호작용 기능을 추가해야 합니다(모달 띄우기).

**Comment by hatchling13** [comment]
검색의 경우, 별도로 내부에 페이지를 만들어야 하므로 이후 추가 이슈를 만들어 작업하겠습니다.

**Comment by hatchling13** [comment]
## 추가로 할 일
### 별도 이슈 생성이 필요한 작업
1. 모달 관련 공통 컴포넌트가 분리된 이후, FAB의 상호작용 기능 작성
2. 디자인 상에 추가된 이후, 게시글 목록의 '더보기' 기능 작성
### 그 외
1. '지역' 및 '카테고리' 선택을 위한 사용자 인터페이스를 작성해야 합니다.
2. 테스트 코드 작성 및 MSW를 활용한 모킹을 적용해야 합니다.
