### ISSUE TITLE
팝 오버 컴포넌트 생성

### ISSUE THREAD

**Issue by davidktlee** [Kernel360/f1-Yigil#182]
### 📝Description
메인 페이지에 존재하는 FAB(Floating Action Button)를 클릭 했을 때, 헤더의 로그인 했을 경우 프로필 이미지를 클릭 했을 때 나타나는 팝 오버 컴포넌트를 구현합니다.

### ✅Task
- [x] 디자인에 맞게 스타일링 
- [x] 팝 오버 버튼 클릭 시 원하는 동작 구현 및 팝 오버 외부 클릭 시 팝 오버 닫기
- [x] 다른 컴포넌트에서도 사용 가능한 범용성 있는 컴포넌트
- [x] 뒷 배경 스크롤 방지

### ✍️Additional
디자인을 보고 초기에는 [`Radix-UI`](https://www.radix-ui.com/primitives/docs/components/dropdown-menu)를 이용해 팝 오버 컴포넌트를 구현하려고 했으나 생각처럼 동작하지 않아 웹 접근성에서는 조금 떨어질 수 있지만 직접 구현하기로 정욱님과 이야기 했습니다.
- radix를 사용하려 했던 이유
1. 뛰어난 웹 접근성 기능을 포함하고 있기 때문에
2. `unstyled`로 구현하는 사람이 원하는 스타일 대로 구현할 수 있어서
3. 각 ui에 대한 다양한 프로퍼티와 이벤트 제공
4. 전체 라이브러리 다운로드가 아닌 컴포넌트 별 다운로드 (작은 사이즈)
5. 공식 문서의 친절함 (자세한 내용과 설명)
- 직접 구현하게 된 이유
현재 full 사이즈의 웹 개발이 아닌 사이즈를 제한한 웹 개발인데 `radix-ui`의 `portal` 및 `overlay` 태그가 원하는 대로 동작하지 않음.

결국 개발자 경험을 좋게하고 스타일링 및 기능 구현에 대한 공수를 줄이기 위해 라이브러리를 도입하기로 했는데, 
생각했던 것과는 반대로 원하는 대로 동작하지 않아 원하는 대로 동작하게 만들기 위해 더 시간과 노력을 들여야 하는 상황이 발생해 도입을 미루고 직접 구현하는 방법을 선택했습니다.

**Comment by hatchling13** [comment]
현재 구현 상 데스크탑 환경에서 팝 오버가 열린 경우 마우스 없이 이를 닫을 수 있는 방법이 없습니다. 키보드를 통한 탐색은 접근성에 큰 도움을 주기 때문에, 필수적인 기능은 아니지만 ESC 키를 눌렀을 때 팝오버가 닫히는 기능이 있으면 좋을 것 같습니다.
