### ISSUE TITLE
전체 도메인 관련 설계 및 기능 수정

### ISSUE THREAD

**Issue by Uknow928** [Kernel360/f1-Yigil#186]
### 📝Description

기획 변경이 발생함에 따라 설계를 전면적으로 수정할 필요가 있음

### ✅Task
- [ ] course 도메인 관련 crud 기능 수정
- [ ] spot 도메인 관련 crud 기능 수정
- [ ] 기존 post 도메인 관련 코드 수정
