### ISSUE TITLE
yml 파일 수정 및 docker-compose, nginx, certbot 적용

### ISSUE THREAD

**Issue by minson96** [Kernel360/f1-Yigil#195]
### 📝Description

- yml 내용에 대해 추가해야하는 내용 (snake-case, webhook 변경, 멀티 모듈에 의한 포트 암호화)
- docker-compose.yml 내용 변화로 인한 수정 (암호화로 직접적으로 파일 추가 없음)
- nginx.conf 사용하여 backend 및 frontend 로드 밸런싱 및 certbot으로 ssl 적용

### ✅Task
- [X] application.yml 내용 수정 및 암호화
- [X] docker-compose.yml 수정 및 암호화
- [X] nginx.conf 파일 수정 및 암호화

### ✍️Additional
- 암호화 되어 있는 파일이 많아 실질적인 변경점이 없을 수 있으나 실제 배포과정에서 동작하는 대부분의 스크립트가 존재해 혹여나 모르시는 내용이 있을 경우 질문 주시면 감사하겠습니다.
