### ISSUE TITLE
별점 추가 컴포넌트

### ISSUE THREAD

**Issue by davidktlee** [Kernel360/f1-Yigil#208]
### 📝Description
처음에는 별점을 보여주는 디자인과 별점을 입력하는 디자인이 있었는데 별점을 입력하는 디자인만 사용됨에 따라 별점을 추가하는 컴포넌트만을 생성합니다.
기본 1점으로 설정 해두었습니다.

### ✅Task
- [x] 별점 추가 스타일링 
- [x] 별점 호버 및 클릭 시 스타일링
- [x] 클릭 시 클릭된 별점 상태에 저장

### ✍️Additional
유저가 클릭했을 때 실제 api 요청을 보내기 위해 사용하는 별점 데이터는 컴포넌트 상위에 위치시켜 set 함수를 내려주는 방법을 사용해야 할 것 같습니다.
