### ISSUE TITLE
장소/코스 추가 단계 탐색 UI

### ISSUE THREAD

**Issue by hatchling13** [Kernel360/f1-Yigil#217]
### 📝Description
장소/코스 추가 시 사용자 입력을 받기 위한 각 단계를 탐색할 수 있는 사용자 인터페이스를 작성합니다.

### ✅Task
- [ ] '탐색할 수 있는 단계'에 대한 상태를 어떤 형태로 관리할지 정합니다.
- [ ] 현재 단계의 이전 또는 다음 단계로 넘어갈 수 있는 버튼을 만듭니다.
- [ ] 현재 단계에 알맞은 문구를 출력합니다.

### ✍️Additional
- '탐색할 수 있는 단계' 상태는 당장 확정짓는 것이 아닌, 구현을 계속해가며 가장 적절한 형태를 찾아야 합니다.
