### ISSUE TITLE
멤버 도메인 수정

### ISSUE THREAD

**Issue by minson96** [Kernel360/f1-Yigil#224]
### 📝Description

- 멤버 entity에 ages, gender, favoritArea 추가 및 MemberUpdateResponse 수정일 필요함.

### ✅Task
- [ ] favoriteArea 추가
- [ ] 멤버 entity 수정
- [ ] MemberService에 MemberCourseList, MemberSpotList 추가
- [ ] MemberUpdateResponse 수정
- [ ] 변경 사항에 대한
