### ISSUE TITLE
경로 추가 시 장소 순차 선택 버튼 (가제) 구현

### ISSUE THREAD

**Issue by davidktlee** [Kernel360/f1-Yigil#226]
### 📝Description
경로 추가 시 사용하는 장소 순서를 선택하는 버튼을 구현합니다.
추가한 장소 개수에 따라 (최대 5개) 번호 색상이 스타일링 되며 별점과 리뷰 선택 창에서는 일정 선택도 가능하게 만들어야 합니다.
장소, 별점, 리뷰가 렌더링 될 때마다 (다음으로 이동할 때마다) 새로 렌더링 하게 만들어 1번으로 가게 만들면 될 것 같습니다.

### ✅Task
- [x] 선택 버튼 스타일링
- [x] 일정 버튼 스타일링 및 조건부 렌더링
- [x] 순서 선택에 따른 인덱스 값 set

### ✍️Additional
한 화면 내의 여러 컴포넌트를 정욱님과 각각 코드를 작성하다보니 조립해서 사용할 때 충분한 대화가 필요할 것으로 보입니다.
