### ISSUE TITLE
장소 상세 페이지 작성

### ISSUE THREAD

**Issue by hatchling13** [Kernel360/f1-Yigil#265]
### 📝Description
장소에 대한 상세 정보를 열람할 수 있는 장소 상세 페이지를 작성합니다.

### ✅Task
- [x] 장소 정보를 표시하는 컴포넌트
  - [x] 장소 이름, 대표 이미지, 리뷰 수, 좋아요 수, 평점, 지도, 주소
- [x] 나의 장소 기록 존재 여부에 따른 UI
  - [x] 기록 존재 시, 사용자가 작성한 장소 기록 정보를 표시하는 컴포넌트
  - [x] 기록 존재하지 않을 시, 장소 기록을 유도하는 컴포넌트
- [x] 리뷰 목록 컴포넌트
  - [x] 타 사용자가 작성한 리뷰를 보여주는 컴포넌트
    - [x] 공통 : 작성자 정보, 별점, 날짜
    - [x] 장소에 대한 리뷰 : 장소 이미지 목록
    - [x] ~~코스에 대한 리뷰 : 경로가 기록된 지도 이미지~~
      - 코스는 이후에 별도로 작업하게 되었음
- [x] 댓글 목록 컴포넌트
  - [x] 댓글 작성자, 내용, 작성 일자, ~~나의 좋아요 여부~~
  - ~~[ ] 답글 작성자, 내용, 작성 일자~~
  - ~~[ ] 댓글/답글 입력 컴포넌트~~
- [x] 좋아요 컴포넌트
