### ISSUE TITLE
feat: 주변 장소 검색을 위한 API 작성

### ISSUE THREAD

**Issue by stoneHee99** [Kernel360/f1-Yigil#365]
### 📝Description
- 주변 장소 검색을 위해 API를 작성합니다.

### ✅Task
- [x] 주변 장소 검색 기능 추가 
- [x] 테스트 코드 검증
- [x] API 문서 작성
