### ISSUE TITLE
어드민 게시글 관리

### ISSUE THREAD

**Issue by ShineCorine** [Kernel360/f1-Yigil#411]
### 📝Description
어드민의 게시글 목록 조회, 게시글 상세 조회, 게시글 삭제 기능을 구현합니다.

### ✅Task
- [x] 스팟 리스트 조회
- [x] 스팟 상세 조회
- [x] 스팟 삭제
- [x] 코스 리스트 조회
- [x] 코스 상세 조회
- [x] 코스 삭제
- [ ] #429
- [x] #428
