### ISSUE TITLE
Course 검색을 위한 API 작성

### ISSUE THREAD

**Issue by stoneHee99** [Kernel360/f1-Yigil#430]
### 📝Description
- Course 검색 화면을 위한 API를 작성합니다

### ✅Task
- [x] 코스 검색 API 
- [x] 테스트 코드 검증 
- [x] API 문서 작성
