### ISSUE TITLE
멤버 성별, 나이 관련 request, response dto 변경

### ISSUE THREAD

**Issue by ShineCorine** [Kernel360/f1-Yigil#494]
### ✅Task
- [x] 나이는 string으로 10, 20, 30 등의 값으로 요청. 응답은 10대, 20대, 30대, 없음 등으로 함
- [x] 성별은 변경 요쳥시 string으로 male/female 로 요청. 응답은 남성, 여성, 없음 등으로 함.
- [x] 수정된 사항만 입력하고 기존의 값을 그대로 둘 경우 요청을 보내지 않도록 함.
