### ISSUE TITLE
hotfix : gender / age 프론트에 응답  변경

### ISSUE THREAD

**Issue by ShineCorine** [Kernel360/f1-Yigil#515]
### ✅Task
- [ ] 연령 10대, 20대, 30대를 10, 20, 30으로 변경
- [ ] 성별 남성, 여성을 male, female 
- [ ] 지역 이름 구분자를 " " 에서 "|"로 변경
