### ISSUE TITLE
기본 엔티티 설계

### ISSUE THREAD

**Issue by stoneHee99** [Kernel360/f1-Yigil#63]
### 📝Description
차주 월요일 기능 작성을 위한 예시 엔티티를 설계합니다.
jts에서 제공해주는 geometry 객체에 대한 이해를 돕기 위해 예시 엔티티 작성 및 데이터베이스와 잘 연동되는지를 검증합니다.

### ✅Task
- [x] 단일 장소 및 그에 대한 정보를 저장하는 Spot 엔티티 설계
- [x] 여러 Spot 및 그 순서와 경로에 대한 정보를 저장하는 Course 엔티티 설계
- [x] 해당 정보들을 화면에 뿌려주는 하나의 단위인 Post 엔티티 설계
- [x] 복잡한 관계를 맺고 있는 엔티티를 확장성 있는 구조로 설계
- [x] 해당 엔티티가 데이터베이스에 잘 저장되고 동장하는지 확인

### ✍️Additional
- Todo: 
- Process:

**Comment by corazzon** [comment]
주말 늦은 시간에 고생 많으셨습니다.

**Comment by stoneHee99** [comment]
> 주말 늦은 시간에 고생 많으셨습니다.

감사합니다~!
