### ISSUE TITLE
헤더 디자인 변경에 따른 재작성

### ISSUE THREAD

**Issue by davidktlee** [Kernel360/f1-Yigil#81]
### 📝Description
헤더 페이지 디자인 변경에 따른 헤더 컴포넌트 재작성

### ✅Task
- [x] 헤더 컴포넌트 스타일링
- [x] 검색 및 알림 페이지 라우팅 처리 -> 삭제
- [ ] 스크롤에 따른 헤더 사이즈 변경 -> 구현 여부 논의 후 결정
- [x] 로고 클릭 시 메인 페이지로 라우팅
- [x] 회원 이미지 클릭 시 미 로그인 시 로그인 페이지, 로그인 마이 페이지로 라우팅 -> 논의 후 결정

### ✍️Additional
- 메인 페이지에만 존재하던 헤더 컴포넌트를 전체 레이아웃에서 사용할 것으로 보여 루트 레이아웃에 위치시켜야 할 것 같음.
- 로그인 전에 헤더에 보여지는 회원 이미지를 어떤 이미지로 처리할지도 논의가 되어야 할 것 같음.
