### ISSUE TITLE
로그를 위한 로그관점의 AOP 클래스 작성

### ISSUE THREAD

**Issue by stoneHee99** [Kernel360/f1-Yigil#97]
### 📝Description
오늘 하루 프론트와의 요청을 주고 받으면서 로그의 소중함을 깨달았습니다.
로그 기능 활성화 및 모니터링을 위해 Spring AOP를 통한 로깅 기능을 추가합니다.

### ✅Task
- [x] 전역적으로 발생하는 요청과 응답에 대한 로그 기능 활성화
- [x] 성능 측정 및 장애 탐지를 위한 로그 기능 활성화
- [x] DB 연결 및 쿼리를 탐지하는 로그 기능 활성화 

### ✍️Additional
로그 레벨에 대해서는 더 이야기를 나눌 필요가 있습니다.
현재 로그레벨 선정 기준은 이러합니다.
- Fatal : Fatal 에러는 실제로 로그에 남기도 전에 서버에 영향을 미치거나 서버가 꺼질 수 있으므로 고려하지 않습니다.
- Error : 예상하지 못한 Error가 발생 시 Error 레벨로 로깅합니다.
- Warn : 예상되는 Error가 발생 시 (예를 들어 Exception handler로 예상된 응답으로 반환되는 경우) Warn 레벨로 로깅합니다.
- INFO : 특별히 모니터링에 필요한 정보들을 로깅합니다.
- DEBUG : 프로그램의 동작 흐름을 판단하기 위한 정보들을 로깅합니다.
- TRACE : 고려하지 않습니다.
